CREATE TABLE IF NOT EXISTS base_teste (
    "CPF" VARCHAR(20),
    "PRIVATE" INT,
    "INCOMPLETO" INT,
    "DATA_ULTIMA_COMPRA" VARCHAR(20),
    "TICKET_MEDIO" FLOAT,
    "TICKET_ULTIMA COMPRA"  FLOAT,
    "LOJA_MAIS_FREQUENTE" VARCHAR(40),
    "LOJA_ULTIMA_COMPRA" VARCHAR(40)
);
